# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from threading import Thread
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import *
from ui_settings_window import Ui_Settings_form
import sys
import serial
from PyQt5.QtCore import (Qt, QObject, QThread, pyqtSignal)

class SettingsWindow(QtWidgets.QWidget, Ui_Settings_form): 
    def __init__(self, parent):
        super().__init__()
        self.setupUi(self)                                                   # +++
        self.parent = parent
        #MainWindow.setObjectName("MainWindow2")
        self.add_function()
                
    def add_function(self):
        self.btn_save_settings.clicked.connect(lambda: self.save_settings())

    def save_settings(self):
        self.parent.widget.close()
        print("Test setting save")
        self.parent.thread.set_baudrate(int(self.comboBox_baudrate.currentIndex()))
        print("Baudrate: " + str(self.comboBox_baudrate.currentIndex()))
        self.parent.set_combobox_bauderate()
        self.parent.comboBox_baudrate.setCurrentIndex(self.comboBox_baudrate.currentIndex())
        #self.parent.thread.set_port(self.comboBox_num_port.currentText())
        print(self.comboBox_baudrate.currentText())
        print(self.comboBox_num_port.currentText())
        