# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 250)
        MainWindow.setStyleSheet("background-color: rgb(22, 23, 29);\n"
"color: rgb(145, 147, 150);\n"
"    ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_disconnect.setGeometry(QtCore.QRect(440, 110, 101, 41))
        self.btn_disconnect.setStyleSheet("QPushButton\n"
"{\n"
"   background-color: rgb(61, 63, 69);\n"
"   color: rgb(145, 147, 150);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"   background-color:white;\n"
"   color: rgb(145, 147, 150);\n"
"}")
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.btn_header_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_header_settings.setGeometry(QtCore.QRect(520, 17, 21, 21))
        self.btn_header_settings.setStyleSheet("image: url(:/newPrefix/img/settings_ico.png) stretch;")
        self.btn_header_settings.setText("")
        self.btn_header_settings.setObjectName("btn_header_settings")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 550, 50))
        self.header.setStyleSheet("background-color: rgb(36, 37, 43);")
        self.header.setText("")
        self.header.setObjectName("header")
        self.richEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.richEdit.setGeometry(QtCore.QRect(0, 50, 430, 175))
        self.richEdit.setStyleSheet("color: rgb(145, 147, 150);")
        self.richEdit.setObjectName("richEdit")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setGeometry(QtCore.QRect(440, 60, 101, 41))
        self.btn_connect.setStyleSheet("QPushButton\n"
"{\n"
"   background-color: rgb(61, 63, 69);\n"
"   color: rgb(145, 147, 150);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"   background-color:white;\n"
"   color: rgb(145, 147, 150);\n"
"}")
        self.btn_connect.setObjectName("btn_connect")
        self.btn_file_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_file_save.setGeometry(QtCore.QRect(440, 190, 101, 41))
        self.btn_file_save.setStyleSheet("QPushButton\n"
"{\n"
"   background-color: rgb(61, 63, 69);\n"
"   color: rgb(145, 147, 150);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"   background-color:white;\n"
"   color: rgb(145, 147, 150);\n"
"}")
        self.btn_file_save.setObjectName("btn_file_save")
        self.btn_state = QtWidgets.QPushButton(self.centralwidget)
        self.btn_state.setGeometry(QtCore.QRect(10, 17, 21, 21))
        self.btn_state.setStyleSheet("background-color: rgb(255, 112, 93);\n"
"/*background-color: rgb(94, 255, 35);*/")
        self.btn_state.setText("")
        self.btn_state.setObjectName("btn_state")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 20, 71, 16))
        self.label_2.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 20, 31, 16))
        self.label_4.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.label_4.setIndent(5)
        self.label_4.setObjectName("label_4")
        self.comboBox_baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_baudrate.setGeometry(QtCore.QRect(270, 16, 91, 22))
        self.comboBox_baudrate.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_num_port = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_num_port.setGeometry(QtCore.QRect(90, 16, 91, 22))
        self.comboBox_num_port.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.comboBox_num_port.setObjectName("comboBox_num_port")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(490, 18, 21, 21))
        self.btn_clear.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"   background-color: rgb(187, 200, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"   background-color:white;\n"
"   color: rgb(145, 147, 150);\n"
"}")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_disconnect.raise_()
        self.header.raise_()
        self.btn_header_settings.raise_()
        self.richEdit.raise_()
        self.btn_connect.raise_()
        self.btn_file_save.raise_()
        self.btn_state.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.comboBox_baudrate.raise_()
        self.comboBox_num_port.raise_()
        self.btn_clear.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Terminal"))
        self.btn_disconnect.setText(_translate("MainWindow", "Отключиться"))
        self.btn_connect.setText(_translate("MainWindow", "Подключиться"))
        self.btn_file_save.setText(_translate("MainWindow", "Сохранить файл"))
        self.label_2.setText(_translate("MainWindow", "Baude Rate"))
        self.label_4.setText(_translate("MainWindow", "Port"))
        self.btn_clear.setText(_translate("MainWindow", "CLR"))
import font_rc
import image_rc
