# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings_form(object):
    def setupUi(self, Settings_form):
        Settings_form.setObjectName("Settings_form")
        Settings_form.resize(262, 300)
        Settings_form.setStyleSheet("background-color: rgb(22, 23, 29);\n"
"color: rgb(145, 147, 150);\n"
"")
        self.btn_save_settings = QtWidgets.QPushButton(Settings_form)
        self.btn_save_settings.setGeometry(QtCore.QRect(80, 230, 101, 41))
        self.btn_save_settings.setStyleSheet("background-color: rgb(61, 63, 69);\n"
"color: rgb(145, 147, 150);")
        self.btn_save_settings.setObjectName("btn_save_settings")
        self.label_2 = QtWidgets.QLabel(Settings_form)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 91, 16))
        self.label_2.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.comboBox_baudrate = QtWidgets.QComboBox(Settings_form)
        self.comboBox_baudrate.setGeometry(QtCore.QRect(130, 16, 91, 22))
        self.comboBox_baudrate.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.label_3 = QtWidgets.QLabel(Settings_form)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 91, 16))
        self.label_3.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.label_3.setIndent(5)
        self.label_3.setObjectName("label_3")
        self.comboBox_num_port = QtWidgets.QComboBox(Settings_form)
        self.comboBox_num_port.setGeometry(QtCore.QRect(130, 46, 91, 22))
        self.comboBox_num_port.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.comboBox_num_port.setObjectName("comboBox_num_port")
        self.checkb_auto_port = QtWidgets.QCheckBox(Settings_form)
        self.checkb_auto_port.setGeometry(QtCore.QRect(130, 80, 70, 17))
        self.checkb_auto_port.setText("")
        self.checkb_auto_port.setObjectName("checkb_auto_port")
        self.label_4 = QtWidgets.QLabel(Settings_form)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 91, 16))
        self.label_4.setStyleSheet("color: rgb(145, 147, 150);\n"
"background-color: rgb(61, 63, 69);")
        self.label_4.setIndent(5)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Settings_form)
        QtCore.QMetaObject.connectSlotsByName(Settings_form)

    def retranslateUi(self, Settings_form):
        _translate = QtCore.QCoreApplication.translate
        Settings_form.setWindowTitle(_translate("Settings_form", "Settings"))
        self.btn_save_settings.setText(_translate("Settings_form", "Сохранить файл"))
        self.label_2.setText(_translate("Settings_form", "Baude Rate"))
        self.label_3.setText(_translate("Settings_form", "Port"))
        self.label_4.setText(_translate("Settings_form", "Auto port"))
